/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'pankajpathak' at '5/19/17 12:43 PM' with Gradle 2.13
 *
 * @author pankajpathak, @date 5/19/17 12:43 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
